# Generated by Django 6.0.2 on 2026-05-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracelets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracelet',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='bracelet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bracelets/'),
        ),
    ]
