# Generated by Django 6.0.2 on 2026-05-22 10:24

import django.db.models.deletion
from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations, models


def keep_only_default_admin(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.exclude(username='admin').delete()
    admin, _ = User.objects.get_or_create(username='admin')
    admin.email = 'admin@example.com'
    admin.password = make_password('admin123')
    admin.is_staff = True
    admin.is_superuser = True
    admin.is_active = True
    admin.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bracelets', '0005_make_bracelet_details_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bracelet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='bracelets.bracelet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'bracelet')},
            },
        ),
        migrations.RunPython(keep_only_default_admin, migrations.RunPython.noop),
    ]
